spring:
  datasource:
    username: igor
    url: jdbc:h2:mem:testeBD
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'